runtime: python310
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  app_start_timeout_sec: 300
